### ISSUE TITLE
unable to enter  sub.domain.tld 

### ISSUE THREAD

**Issue by IgorKuleshov** [GFW4Fun/x-ui-pro#14]
unfortunately, I was unable to enter tld. what could be wrong? thanks
Enter available subdomain (sub.domain.tld): irxx.serverxxx.xxoud
Enter available subdomain (sub.domain.tld):

**Comment by puuury** [comment]
i have this problem. can you fix that ?

**Comment by faridRezvani** [comment]
The problem is the lack of configuration and correct dns of the server
Read the article below
https://github.com/hiddify/Hiddify-Manager/wiki/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%D8%AA%D9%86%D8%B8% DB%8C%D9%85-DNS-%D8%B3%D8%B1%D9%88%D8%B1#%D8%AA%D9%86%D8%B8%DB%8C%D9%85-dns- %D8%A7%D8%B2-%D8%B7%D8%B1%DB%8C%D9%82-ssh
