### ISSUE TITLE
About update.

### ISSUE THREAD

**Issue by jn1or** [GFW4Fun/x-ui-pro#29]
Sorry for silly question, but should I regular update anything with this script? 
I mean, after installation on server, besides x-ray and x-ui anything more needs in updates? 
Because I see this script updating everyday. For example if I installed this script 6 months ago. 
My inner perfectionist can't sleep, if something goes wrong or not ideal 😅

**Comment by faridRezvani** [comment]
I thank @jn1or for creating this problem.
My question is the same. Until what day will the most stable version be released?

**Comment by jn1or** [comment]
Yeah, while was writing previous post, actual ver was 6.6.8 atm 7.0.0 two versions was published on same day.

**Comment by GFW4Fun** [comment]
Hi
If you have installed, the update is not necessary!

Because this is the installer script and the program is not!
Update via script no important ! 
But you can Re -run the script to update nginx config  if your installation is too old. (backup before)


Update x-ui through this command > `x-ui update`
Update Linux and apps through this command (nginx,tor,...)>  `apt update && apt upgrade`

> Sorry for silly question, but should I regular update anything with this script? I mean, after installation on server, besides x-ray and x-ui anything more needs in updates? Because I see this script updating everyday. For example if I installed this script 6 months ago. My inner perfectionist can't sleep, if something goes wrong or not ideal 😅
